spring.datasource.url=jdbc:postgresql://dscpocdscatalog20260325-postgresql.cr2wuw2swh0s.us-east-2.rds.amazonaws.com:5432/dscatalogdb
spring.datasource.username=root
spring.datasource.password=Masterkey321

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=none
